name: 'List Members'
description: "GitHub Action to randomly select a number of an organization's members use in other actions. Forked from github.com/RITct/members-list-action"
author: thatsanicehat

inputs:
  org-name:  # id of input
    description: 'Organization Name'
    required: true
  auth-token:
    description: 'An auth token with "read:org" permissions'
    required: true
  team-name:
    description: 'Name of team'
    required: true
  user-limit:
    description: 'How many users to select at random'
    required: false
    default: '2'
outputs:
  users:
    description: "Comma-separated list of users"
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'user'
  color: 'blue'
