name: 'List Members'
description: "GitHub Action to randomly select a number of an organization's members use in other actions. Forked from github.com/RITct/members-list-action"
author: RITct, thatsanicehat

inputs:
  org-name:  # id of input
    description: 'Organization Name'
    required: true
  role-name:
    description: 'Name of role'
    required: true
  user-limit:
    description: 'How many users to select at random'
    required: true
outputs:
  users:
    description: "Comma-separated list of users"
runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'user'
  color: 'blue'
