name: 'List Members'
description: 'List members of an organization and group them by teams'
inputs:
  org-name:  # id of input
    description: 'Organization Name'
    required: true
  file-path: #id of input
    description: 'Json file'
    required: false
    default: "members.json"
  commit-user-name: 
    description: 'Commit Username'
    required: false
    default: "list-member-action"
  commit-user-email:
    description: 'Commit Email'
    required: false
    default: "listaction@noreply.com"
  commit-msg:
    description: 'Commit Message'
    required: false
    default: "changed members file"

runs:
  using: 'node12'
  main: 'index.js'
